name: mobx_generator
description: Annotation build tool for MobX
version: 0.0.1
homepage:
author:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mobx: any
  analyzer: any
  build: any
  source_gen: '>=0.8.0'
  build_config: '>=0.3.0'
  mustache4dart: any

dev_dependencies:
  build_runner: '>=0.9.1'
  test: ^1.0.0

dependency_overrides:
  mobx:
    path: ../mobx